# Use the official Golang image for running tests
FROM golang:1.22-alpine

# Install build tools
RUN apk add --no-cache gcc musl-dev

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code into the container
COPY . .

# Copy the test script
COPY scripts/test.sh .

# Make the test script executable
RUN chmod +x test.sh

# Run the test script
CMD ["./test.sh"]
