version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=local
    depends_on:
      # - db
      - consul

  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: yourpassword
  #     POSTGRES_DB: yourdb
  #   ports:
  #     - "5432:5432"

  consul:
    image: consul:1.9.5
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
