version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - APP_ENV=test
    depends_on:
      - consul

  consul:
    image: consul:1.9.5
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
